// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.22.0
// 	protoc        v3.13.0
// source: cereal_proto/test/oneof.proto

package cereal_test

import (
	proto "github.com/golang/protobuf/proto"
	cereal "github.com/illuscio-dev/protoCereal-go/cereal"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type DecimalList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: bson:"value"
	Value []*cereal.Decimal `protobuf:"bytes,1,rep,name=value,proto3" json:"value,omitempty" bson:"value"`
}

func (x *DecimalList) Reset() {
	*x = DecimalList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cereal_proto_test_oneof_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DecimalList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecimalList) ProtoMessage() {}

func (x *DecimalList) ProtoReflect() protoreflect.Message {
	mi := &file_cereal_proto_test_oneof_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecimalList.ProtoReflect.Descriptor instead.
func (*DecimalList) Descriptor() ([]byte, []int) {
	return file_cereal_proto_test_oneof_proto_rawDescGZIP(), []int{0}
}

func (x *DecimalList) GetValue() []*cereal.Decimal {
	if x != nil {
		return x.Value
	}
	return nil
}

type HasCustomOneOf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: bson:"many"
	//
	// Types that are assignable to Many:
	//	*HasCustomOneOf_DecimalValue
	//	*HasCustomOneOf_StringValue
	//	*HasCustomOneOf_DecimalList
	Many isHasCustomOneOf_Many `protobuf_oneof:"many" bson:"many"`
}

func (x *HasCustomOneOf) Reset() {
	*x = HasCustomOneOf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cereal_proto_test_oneof_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HasCustomOneOf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasCustomOneOf) ProtoMessage() {}

func (x *HasCustomOneOf) ProtoReflect() protoreflect.Message {
	mi := &file_cereal_proto_test_oneof_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasCustomOneOf.ProtoReflect.Descriptor instead.
func (*HasCustomOneOf) Descriptor() ([]byte, []int) {
	return file_cereal_proto_test_oneof_proto_rawDescGZIP(), []int{1}
}

func (m *HasCustomOneOf) GetMany() isHasCustomOneOf_Many {
	if m != nil {
		return m.Many
	}
	return nil
}

func (x *HasCustomOneOf) GetDecimalValue() *cereal.Decimal {
	if x, ok := x.GetMany().(*HasCustomOneOf_DecimalValue); ok {
		return x.DecimalValue
	}
	return nil
}

func (x *HasCustomOneOf) GetStringValue() string {
	if x, ok := x.GetMany().(*HasCustomOneOf_StringValue); ok {
		return x.StringValue
	}
	return ""
}

func (x *HasCustomOneOf) GetDecimalList() *DecimalList {
	if x, ok := x.GetMany().(*HasCustomOneOf_DecimalList); ok {
		return x.DecimalList
	}
	return nil
}

type isHasCustomOneOf_Many interface {
	isHasCustomOneOf_Many()
}

type HasCustomOneOf_DecimalValue struct {
	DecimalValue *cereal.Decimal `protobuf:"bytes,1,opt,name=decimal_value,json=decimalValue,proto3,oneof"`
}

type HasCustomOneOf_StringValue struct {
	StringValue string `protobuf:"bytes,2,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type HasCustomOneOf_DecimalList struct {
	DecimalList *DecimalList `protobuf:"bytes,3,opt,name=decimal_list,json=decimalList,proto3,oneof"`
}

func (*HasCustomOneOf_DecimalValue) isHasCustomOneOf_Many() {}

func (*HasCustomOneOf_StringValue) isHasCustomOneOf_Many() {}

func (*HasCustomOneOf_DecimalList) isHasCustomOneOf_Many() {}

type HasOneOfBytes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Value:
	//	*HasOneOfBytes_BytesValue
	//	*HasOneOfBytes_StringValue
	Value isHasOneOfBytes_Value `protobuf_oneof:"value"`
}

func (x *HasOneOfBytes) Reset() {
	*x = HasOneOfBytes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cereal_proto_test_oneof_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HasOneOfBytes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasOneOfBytes) ProtoMessage() {}

func (x *HasOneOfBytes) ProtoReflect() protoreflect.Message {
	mi := &file_cereal_proto_test_oneof_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasOneOfBytes.ProtoReflect.Descriptor instead.
func (*HasOneOfBytes) Descriptor() ([]byte, []int) {
	return file_cereal_proto_test_oneof_proto_rawDescGZIP(), []int{2}
}

func (m *HasOneOfBytes) GetValue() isHasOneOfBytes_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *HasOneOfBytes) GetBytesValue() []byte {
	if x, ok := x.GetValue().(*HasOneOfBytes_BytesValue); ok {
		return x.BytesValue
	}
	return nil
}

func (x *HasOneOfBytes) GetStringValue() string {
	if x, ok := x.GetValue().(*HasOneOfBytes_StringValue); ok {
		return x.StringValue
	}
	return ""
}

type isHasOneOfBytes_Value interface {
	isHasOneOfBytes_Value()
}

type HasOneOfBytes_BytesValue struct {
	BytesValue []byte `protobuf:"bytes,1,opt,name=bytes_value,json=bytesValue,proto3,oneof"`
}

type HasOneOfBytes_StringValue struct {
	StringValue string `protobuf:"bytes,2,opt,name=string_value,json=stringValue,proto3,oneof"`
}

func (*HasOneOfBytes_BytesValue) isHasOneOfBytes_Value() {}

func (*HasOneOfBytes_StringValue) isHasOneOfBytes_Value() {}

var File_cereal_proto_test_oneof_proto protoreflect.FileDescriptor

var file_cereal_proto_test_oneof_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x63, 0x65, 0x72, 0x65, 0x61, 0x6c, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74,
	0x65, 0x73, 0x74, 0x2f, 0x6f, 0x6e, 0x65, 0x6f, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0b, 0x63, 0x65, 0x72, 0x65, 0x61, 0x6c, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x63, 0x65,
	0x72, 0x65, 0x61, 0x6c, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x65, 0x63, 0x69, 0x6d,
	0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x34, 0x0a, 0x0b, 0x44, 0x65, 0x63, 0x69,
	0x6d, 0x61, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x63, 0x65, 0x72, 0x65, 0x61, 0x6c, 0x2e,
	0x44, 0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0xb4,
	0x01, 0x0a, 0x0e, 0x48, 0x61, 0x73, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x4f, 0x6e, 0x65, 0x4f,
	0x66, 0x12, 0x36, 0x0a, 0x0d, 0x64, 0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c, 0x5f, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x63, 0x65, 0x72, 0x65, 0x61,
	0x6c, 0x2e, 0x44, 0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c, 0x48, 0x00, 0x52, 0x0c, 0x64, 0x65, 0x63,
	0x69, 0x6d, 0x61, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x23, 0x0a, 0x0c, 0x73, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x00, 0x52, 0x0b, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x3d,
	0x0a, 0x0c, 0x64, 0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x63, 0x65, 0x72, 0x65, 0x61, 0x6c, 0x5f, 0x74, 0x65,
	0x73, 0x74, 0x2e, 0x44, 0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x00,
	0x52, 0x0b, 0x64, 0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x06, 0x0a,
	0x04, 0x6d, 0x61, 0x6e, 0x79, 0x22, 0x60, 0x0a, 0x0d, 0x48, 0x61, 0x73, 0x4f, 0x6e, 0x65, 0x4f,
	0x66, 0x42, 0x79, 0x74, 0x65, 0x73, 0x12, 0x21, 0x0a, 0x0b, 0x62, 0x79, 0x74, 0x65, 0x73, 0x5f,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x0a, 0x62,
	0x79, 0x74, 0x65, 0x73, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x23, 0x0a, 0x0c, 0x73, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x00, 0x52, 0x0b, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x07,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x34, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x6c, 0x6c, 0x75, 0x73, 0x63, 0x69, 0x6f, 0x2d, 0x64,
	0x65, 0x76, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x43, 0x65, 0x72, 0x65, 0x61, 0x6c, 0x2d, 0x67,
	0x6f, 0x2f, 0x63, 0x65, 0x72, 0x65, 0x61, 0x6c, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cereal_proto_test_oneof_proto_rawDescOnce sync.Once
	file_cereal_proto_test_oneof_proto_rawDescData = file_cereal_proto_test_oneof_proto_rawDesc
)

func file_cereal_proto_test_oneof_proto_rawDescGZIP() []byte {
	file_cereal_proto_test_oneof_proto_rawDescOnce.Do(func() {
		file_cereal_proto_test_oneof_proto_rawDescData = protoimpl.X.CompressGZIP(file_cereal_proto_test_oneof_proto_rawDescData)
	})
	return file_cereal_proto_test_oneof_proto_rawDescData
}

var file_cereal_proto_test_oneof_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_cereal_proto_test_oneof_proto_goTypes = []interface{}{
	(*DecimalList)(nil),    // 0: cereal_test.DecimalList
	(*HasCustomOneOf)(nil), // 1: cereal_test.HasCustomOneOf
	(*HasOneOfBytes)(nil),  // 2: cereal_test.HasOneOfBytes
	(*cereal.Decimal)(nil), // 3: cereal.Decimal
}
var file_cereal_proto_test_oneof_proto_depIdxs = []int32{
	3, // 0: cereal_test.DecimalList.value:type_name -> cereal.Decimal
	3, // 1: cereal_test.HasCustomOneOf.decimal_value:type_name -> cereal.Decimal
	0, // 2: cereal_test.HasCustomOneOf.decimal_list:type_name -> cereal_test.DecimalList
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_cereal_proto_test_oneof_proto_init() }
func file_cereal_proto_test_oneof_proto_init() {
	if File_cereal_proto_test_oneof_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cereal_proto_test_oneof_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DecimalList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cereal_proto_test_oneof_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HasCustomOneOf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cereal_proto_test_oneof_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HasOneOfBytes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_cereal_proto_test_oneof_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*HasCustomOneOf_DecimalValue)(nil),
		(*HasCustomOneOf_StringValue)(nil),
		(*HasCustomOneOf_DecimalList)(nil),
	}
	file_cereal_proto_test_oneof_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*HasOneOfBytes_BytesValue)(nil),
		(*HasOneOfBytes_StringValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cereal_proto_test_oneof_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cereal_proto_test_oneof_proto_goTypes,
		DependencyIndexes: file_cereal_proto_test_oneof_proto_depIdxs,
		MessageInfos:      file_cereal_proto_test_oneof_proto_msgTypes,
	}.Build()
	File_cereal_proto_test_oneof_proto = out.File
	file_cereal_proto_test_oneof_proto_rawDesc = nil
	file_cereal_proto_test_oneof_proto_goTypes = nil
	file_cereal_proto_test_oneof_proto_depIdxs = nil
}
